### Создать вопрос 1
GET http://localhost:8080/exam/java/add?question=Вопрос1&answer=Ответ1
### Создать вопрос 2
GET http://localhost:8080/exam/java/add?question=Вопрос2&answer=Ответ2
### Создать вопрос 3
GET http://localhost:8080/exam/java/add?question=Вопрос3&answer=Ответ3
### Создать вопрос 4
GET http://localhost:8080/exam/java/add?question=Вопрос4&answer=Ответ4
### Создать вопрос 5
GET http://localhost:8080/exam/java/add?question=Вопрос5&answer=Ответ5
### Создать некорректный вопрос
GET http://localhost:8080/exam/java/add?question=&answer=

### Получить все вопросы
GET http://localhost:8080/exam/java
